"""create table friendsUser sendFriendRequests

Revision ID: 8cd7aa0a36fd
Revises: 
Create Date: 2025-10-09 17:32:01.224069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd7aa0a36fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendsUser',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('addition_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'addition_number', name='uq_user_addition'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend'),
    schema='friends'
    )
    op.create_index(op.f('ix_friends_friendsUser_addition_number'), 'friendsUser', ['addition_number'], unique=False, schema='friends')
    op.create_index(op.f('ix_friends_friendsUser_friend_id'), 'friendsUser', ['friend_id'], unique=False, schema='friends')
    op.create_index(op.f('ix_friends_friendsUser_user_id'), 'friendsUser', ['user_id'], unique=False, schema='friends')
    op.create_index('ix_user_addition', 'friendsUser', ['user_id', 'addition_number'], unique=False, schema='friends')
    op.create_table('sendFriendRequests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_user_id', name='uq_user_request'),
    schema='friends'
    )
    op.create_index(op.f('ix_friends_sendFriendRequests_request_user_id'), 'sendFriendRequests', ['request_user_id'], unique=False, schema='friends')
    op.create_index(op.f('ix_friends_sendFriendRequests_send_at'), 'sendFriendRequests', ['send_at'], unique=False, schema='friends')
    op.create_index(op.f('ix_friends_sendFriendRequests_user_id'), 'sendFriendRequests', ['user_id'], unique=False, schema='friends')
    op.create_index('ix_user_send_at', 'sendFriendRequests', ['user_id', 'send_at'], unique=False, schema='friends')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_send_at', table_name='sendFriendRequests', schema='friends')
    op.drop_index(op.f('ix_friends_sendFriendRequests_user_id'), table_name='sendFriendRequests', schema='friends')
    op.drop_index(op.f('ix_friends_sendFriendRequests_send_at'), table_name='sendFriendRequests', schema='friends')
    op.drop_index(op.f('ix_friends_sendFriendRequests_request_user_id'), table_name='sendFriendRequests', schema='friends')
    op.drop_table('sendFriendRequests', schema='friends')
    op.drop_index('ix_user_addition', table_name='friendsUser', schema='friends')
    op.drop_index(op.f('ix_friends_friendsUser_user_id'), table_name='friendsUser', schema='friends')
    op.drop_index(op.f('ix_friends_friendsUser_friend_id'), table_name='friendsUser', schema='friends')
    op.drop_index(op.f('ix_friends_friendsUser_addition_number'), table_name='friendsUser', schema='friends')
    op.drop_table('friendsUser', schema='friends')
    # ### end Alembic commands ###
