"""create tables messages chatParticipants userChats

Revision ID: e3c05e7a5a4f
Revises: 
Create Date: 2025-10-08 15:07:36.307107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c05e7a5a4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userChats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_userChats_chat_id'), 'userChats', ['chat_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_userChats_created_at'), 'userChats', ['created_at'], unique=False, schema='chat')
    op.create_table('chatParticipants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.userChats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_user'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chatParticipants_chat_id'), 'chatParticipants', ['chat_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_chatParticipants_user_id'), 'chatParticipants', ['user_id'], unique=False, schema='chat')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.userChats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['chat.chatParticipants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_messages_chat_message_id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'messages', ['chat_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_created_at'), 'messages', ['created_at'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_message_id'), 'messages', ['message_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_participant_id'), 'messages', ['participant_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_messages_send_at'), 'messages', ['send_at'], unique=False, schema='chat')
    op.create_index('ix_messages_chat_send_at', 'messages', ['chat_id', 'send_at'], unique=False, schema='chat')
    op.create_index('ix_messages_participant_send_at', 'messages', ['participant_id', 'send_at'], unique=False, schema='chat')
    op.drop_table('alembic_version', schema='celery')
    op.drop_table('secretKeyJWT', schema='celery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretKeyJWT',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_key', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('change_key', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('secretKeyJWT_pkey')),
    schema='celery'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='celery'
    )
    op.drop_index('ix_messages_participant_send_at', table_name='messages', schema='chat')
    op.drop_index('ix_messages_chat_send_at', table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_send_at'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_participant_id'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='messages', schema='chat')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='messages', schema='chat')
    op.drop_table('messages', schema='chat')
    op.drop_index(op.f('ix_chat_chatParticipants_user_id'), table_name='chatParticipants', schema='chat')
    op.drop_index(op.f('ix_chat_chatParticipants_chat_id'), table_name='chatParticipants', schema='chat')
    op.drop_table('chatParticipants', schema='chat')
    op.drop_index(op.f('ix_chat_userChats_created_at'), table_name='userChats', schema='chat')
    op.drop_index(op.f('ix_chat_userChats_chat_id'), table_name='userChats', schema='chat')
    op.drop_table('userChats', schema='chat')
    # ### end Alembic commands ###
