import os
import logging
from shared.services.tools.other import load_from_env

logger = logging.getLogger(__name__)

l = load_from_env

POSTGRES_URL = l("POSTGRES_URL")

ALGORITHM = l("ALGORITHM")
SECRET_KEY = l("SECRET_KEY")
SECRET_KEY_SIZE = int(l("SECRET_KEY_SIZE"))
TOKEN_LIFETIME_DAYS = int(l("TOKEN_LIFETIME_DAYS"))

ACCESS_TOKEN_LIFETIME_MINUTES = int(l("ACCESS_TOKEN_LIFETIME_MINUTES"))
REFRESH_TOKEN_LIFETIME_DAYS = int(l("REFRESH_TOKEN_LIFETIME_DAYS"))

ADMIN_CONFIRMATION_IP = l("ADMIN_CONFIRMATION_IP")

RABBITMQ_URL = l("RABBITMQ_URL")
