services:
  service_profile:
    build:
      context: ..
      dockerfile: service_profile/Dockerfile
    ports: 
      - "${SERVICE_PROFILE_PORT}:${SERVICE_PROFILE_PORT}"
    env_file:
      - "../.env"
    networks:
      - app_net

networks:
  app_net:
    external: true