"""create table secretKeyJWT

Revision ID: d1b699f1cb9f
Revises: 
Create Date: 2025-10-09 17:36:09.776622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b699f1cb9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretKeyJWT',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('created_key', sa.DateTime(), nullable=False),
    sa.Column('change_key', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='celery'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretKeyJWT', schema='celery')
    # ### end Alembic commands ###
