services:    
  service_frontend:
    build:
      context: .
      dockerfile: service_frontend/Dockerfile

    ports:
      - "8080:80"
    environment:
      SERVICE_FREE_HOST: "${SERVICE_FREE_HOST}"
      SERVICE_FREE_PORT: "${SERVICE_FREE_PORT}"
        
      SERVICE_ADMIN_HOST: "${SERVICE_ADMIN_HOST}"
      SERVICE_ADMIN_PORT: "${SERVICE_ADMIN_PORT}"
        
      SERVICE_CHAT_HOST: "${SERVICE_CHAT_HOST}"
      SERVICE_CHAT_PORT: "${SERVICE_CHAT_PORT}"
        
      SERVICE_FRIENDS_HOST: "${SERVICE_FRIENDS_HOST}"
      SERVICE_FRIENDS_PORT: "${SERVICE_FRIENDS_PORT}"
        
      SERVICE_NOTIFICATIONS_HOST: "${SERVICE_NOTIFICATIONS_HOST}"
      SERVICE_NOTIFICATIONS_PORT: "${SERVICE_NOTIFICATIONS_PORT}"
        
      SERVICE_PROFILE_HOST: "${SERVICE_PROFILE_HOST}"
      SERVICE_PROFILE_PORT: "${SERVICE_PROFILE_PORT}"

      SERVICE_SECURITY_HOST: "${SERVICE_SECURITY_HOST}"
      SERVICE_SECURITY_PORT: "${SERVICE_SECURITY_PORT}"

      SERVICE_SETTINGS_HOST: "${SERVICE_SETTINGS_HOST}"
      SERVICE_SETTINGS_PORT: "${SERVICE_SETTINGS_PORT}"