services:
  service_free:
    build:
      context: ..
      dockerfile: service_free/Dockerfile
    ports: 
      - "${SERVICE_FREE_PORT}:${SERVICE_FREE_PORT}"
    env_file:
      - "../.env"
    networks:
      - app_net

networks:
  app_net:
    external: true