import os
import logging
from shared.services.tools.other import load_from_env

logger = logging.getLogger(__name__)

l = load_from_env

NAME_PROJECT = l("NAME_PROJECT")
POSTGRES_URL = l("POSTGRES_URL")

UPORT = int(l("UPORT"))
UHOST = l("UHOST")

ALGORITHM = l("ALGORITHM")
SECRET_KEY = l("SECRET_KEY")
SECRET_KEY_SIZE = int(l("SECRET_KEY_SIZE"))
TOKEN_LIFETIME_DAYS = int(l("TOKEN_LIFETIME_DAYS"))

ACCESS_TOKEN_LIFETIME_MINUTES = int(l("ACCESS_TOKEN_LIFETIME_MINUTES"))
REFRESH_TOKEN_LIFETIME_DAYS = int(l("REFRESH_TOKEN_LIFETIME_DAYS"))

ADMIN_CONFIRMATION_IP = l("ADMIN_CONFIRMATION_IP")

RABBITMQ_URL = l("RABBITMQ_URL")

HTTP_URL = l("HTTP_URL")

SERVICE_FREE_URL = f'{l("SERVICE_FREE_BASE_URL")}:8004'