services:
  service_friends:
    build:
      context: ..
      dockerfile: service_friends/Dockerfile

    ports: 
      - "${SERVICE_FRIENDS_PORT}:${SERVICE_FRIENDS_PORT}"
    env_file:
      - "../.env"
